steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/r-estimate:latest'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/r-estimate/$BRANCH_NAME/aviatorsbot-scala:$SHORT_SHA'
      - '.'
    timeout: 1500s
images:
  - 'eu.gcr.io/$PROJECT_ID/r-estimate:latest'
  - 'eu.gcr.io/$PROJECT_ID/r-estimate/$BRANCH_NAME/aviatorsbot-scala:$SHORT_SHA'
timeout: 2000s