steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=eu.gcr.io/$PROJECT_ID/r-estimate:latest
    - --cache=true
    - --cache-ttl=96h
    timeout: 1500s
timeout: 2000s
